# Generated by Django 5.1.5 on 2025-01-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrymodel",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
